### ISSUE TITLE
进程保活的弄好了吗

### ISSUE THREAD

**Issue by jiasijie** [naluetuo/loanuncle#1]
进程保活那个怎么用啊大佬

**Comment by naluetuo** [comment]
> 进程保活那个怎么用啊大佬
就用那个keeplive的库就差不多可以满足大部分保活了。但是没办法一直常驻，这个是android现在的难题特别是高版本。

**Comment by jiasijie** [comment]
他那个onWorking  和  onStop  都是干嘛的   是把启动方法放进去吗  

//定义前台服务的默认样式。即标题、描述和图标
        ForegroundNotification foregroundNotification = new ForegroundNotification("测试","描述", R.mipmap.ic_launcher,
                //定义前台服务的通知点击事件
                new ForegroundNotificationClickListener() {

                    @Override
                    public void foregroundNotificationClick(Context context, Intent intent) {
                        startActivity(new Intent(getApplicationContext(),MyServiceBaoHuo.class));
                    }
                });
        //启动保活服务
        KeepLive.startWork(this, KeepLive.RunMode.ENERGY, foregroundNotification,
                //你需要保活的服务，如socket连接、定时任务等，建议不用匿名内部类的方式在这里写
                new KeepLiveService() {
                    /**
                     * 运行中
                     * 由于服务可能会多次自动启动，该方法可能重复调用
                     */
                    @Override
                    public void onWorking() {
                        startActivity(new Intent(getApplicationContext(),MyServiceBaoHuo.class));
                    }
                    /**
                     * 服务终止
                     * 由于服务可能会被多次终止，该方法可能重复调用，需同onWorking配套使用，如注册和注销broadcast
                     */
                    @Override
                    public void onStop() {
                        startActivity(new Intent(getApplicationContext(),MyServiceBaoHuo.class));
                    }
                }
        );

是这么用吗  大佬

**Comment by jiasijie** [comment]
请大佬明示  我主要就是为了接受推送消息
